-- Generated by cargo run --features elm-codegen --bin generate-elm. Do not edit.


module Api.Generated exposing (..)

import Json.Decode
import Json.Encode


type alias SizeInches =
    { width : Float
    , height : Float
    }


sizeInchesEncoder : SizeInches -> Json.Encode.Value
sizeInchesEncoder struct =
    Json.Encode.object
        [ ( "width", Json.Encode.float struct.width )
        , ( "height", Json.Encode.float struct.height )
        ]


sizeInchesDecoder : Json.Decode.Decoder SizeInches
sizeInchesDecoder =
    Json.Decode.succeed SizeInches
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "width" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "height" Json.Decode.float))


type alias MarginsInches =
    { top : Float
    , right : Float
    , bottom : Float
    , left : Float
    }


marginsInchesEncoder : MarginsInches -> Json.Encode.Value
marginsInchesEncoder struct =
    Json.Encode.object
        [ ( "top", Json.Encode.float struct.top )
        , ( "right", Json.Encode.float struct.right )
        , ( "bottom", Json.Encode.float struct.bottom )
        , ( "left", Json.Encode.float struct.left )
        ]


marginsInchesDecoder : Json.Decode.Decoder MarginsInches
marginsInchesDecoder =
    Json.Decode.succeed MarginsInches
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "top" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "right" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "bottom" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "left" Json.Decode.float))


type alias GuttersInches =
    { horizontal : Float
    , vertical : Float
    }


guttersInchesEncoder : GuttersInches -> Json.Encode.Value
guttersInchesEncoder struct =
    Json.Encode.object
        [ ( "horizontal", Json.Encode.float struct.horizontal )
        , ( "vertical", Json.Encode.float struct.vertical )
        ]


guttersInchesDecoder : Json.Decode.Decoder GuttersInches
guttersInchesDecoder =
    Json.Decode.succeed GuttersInches
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "horizontal" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "vertical" Json.Decode.float))


type Orientation
    = OrientationPortrait
    | OrientationLandscape
    | OrientationSquare


orientationEncoder : Orientation -> Json.Encode.Value
orientationEncoder enum =
    case enum of
        OrientationPortrait ->
            Json.Encode.string "portrait"

        OrientationLandscape ->
            Json.Encode.string "landscape"

        OrientationSquare ->
            Json.Encode.string "square"


orientationDecoder : Json.Decode.Decoder Orientation
orientationDecoder =
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "portrait" ->
                            Json.Decode.succeed OrientationPortrait

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "landscape" ->
                            Json.Decode.succeed OrientationLandscape

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "square" ->
                            Json.Decode.succeed OrientationSquare

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]


type OrientationPreference
    = OrientationPreferenceAuto
    | OrientationPreferencePortrait
    | OrientationPreferenceLandscape
    | OrientationPreferenceUpright
    | OrientationPreferenceQuarterTurn


orientationPreferenceEncoder : OrientationPreference -> Json.Encode.Value
orientationPreferenceEncoder enum =
    case enum of
        OrientationPreferenceAuto ->
            Json.Encode.string "auto"

        OrientationPreferencePortrait ->
            Json.Encode.string "portrait"

        OrientationPreferenceLandscape ->
            Json.Encode.string "landscape"

        OrientationPreferenceUpright ->
            Json.Encode.string "upright"

        OrientationPreferenceQuarterTurn ->
            Json.Encode.string "quarterTurn"


orientationPreferenceDecoder : Json.Decode.Decoder OrientationPreference
orientationPreferenceDecoder =
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "auto" ->
                            Json.Decode.succeed OrientationPreferenceAuto

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "portrait" ->
                            Json.Decode.succeed OrientationPreferencePortrait

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "landscape" ->
                            Json.Decode.succeed OrientationPreferenceLandscape

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "upright" ->
                            Json.Decode.succeed OrientationPreferenceUpright

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "quarterTurn" ->
                            Json.Decode.succeed OrientationPreferenceQuarterTurn

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]


type FinishedSizeMode
    = FinishedSizeModeCommon
    | FinishedSizeModeOriginal


finishedSizeModeEncoder : FinishedSizeMode -> Json.Encode.Value
finishedSizeModeEncoder enum =
    case enum of
        FinishedSizeModeCommon ->
            Json.Encode.string "common"

        FinishedSizeModeOriginal ->
            Json.Encode.string "original"


finishedSizeModeDecoder : Json.Decode.Decoder FinishedSizeMode
finishedSizeModeDecoder =
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "common" ->
                            Json.Decode.succeed FinishedSizeModeCommon

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "original" ->
                            Json.Decode.succeed FinishedSizeModeOriginal

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]


type ArtworkFitMode
    = ArtworkFitModeContain
    | ArtworkFitModeCover
    | ArtworkFitModeStretch


artworkFitModeEncoder : ArtworkFitMode -> Json.Encode.Value
artworkFitModeEncoder enum =
    case enum of
        ArtworkFitModeContain ->
            Json.Encode.string "contain"

        ArtworkFitModeCover ->
            Json.Encode.string "cover"

        ArtworkFitModeStretch ->
            Json.Encode.string "stretch"


artworkFitModeDecoder : Json.Decode.Decoder ArtworkFitMode
artworkFitModeDecoder =
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "contain" ->
                            Json.Decode.succeed ArtworkFitModeContain

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "cover" ->
                            Json.Decode.succeed ArtworkFitModeCover

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "stretch" ->
                            Json.Decode.succeed ArtworkFitModeStretch

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]


type alias CropPosition =
    { x : Float
    , y : Float
    }


cropPositionEncoder : CropPosition -> Json.Encode.Value
cropPositionEncoder struct =
    Json.Encode.object
        [ ( "x", Json.Encode.float struct.x )
        , ( "y", Json.Encode.float struct.y )
        ]


cropPositionDecoder : Json.Decode.Decoder CropPosition
cropPositionDecoder =
    Json.Decode.succeed CropPosition
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "x" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "y" Json.Decode.float))


type alias ArtworkFit =
    { mode : ArtworkFitMode
    , position : CropPosition
    }


artworkFitEncoder : ArtworkFit -> Json.Encode.Value
artworkFitEncoder struct =
    Json.Encode.object
        [ ( "mode", artworkFitModeEncoder struct.mode )
        , ( "position", cropPositionEncoder struct.position )
        ]


artworkFitDecoder : Json.Decode.Decoder ArtworkFit
artworkFitDecoder =
    Json.Decode.succeed ArtworkFit
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "mode" artworkFitModeDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "position" cropPositionDecoder))


type alias SourcePage =
    { sourcePdfSize : SizeInches
    , sourceTrimBox : Maybe PdfBox
    , previewBox : Maybe PdfBox
    , physicalSizeAssumed : Bool
    , filename : Maybe String
    , originalPageNumber : Maybe Int
    }


sourcePageEncoder : SourcePage -> Json.Encode.Value
sourcePageEncoder struct =
    Json.Encode.object
        [ ( "sourcePdfSize", sizeInchesEncoder struct.sourcePdfSize )
        , ( "sourceTrimBox", (Maybe.withDefault Json.Encode.null << Maybe.map pdfBoxEncoder) struct.sourceTrimBox )
        , ( "previewBox", (Maybe.withDefault Json.Encode.null << Maybe.map pdfBoxEncoder) struct.previewBox )
        , ( "physicalSizeAssumed", Json.Encode.bool struct.physicalSizeAssumed )
        , ( "filename", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.string) struct.filename )
        , ( "originalPageNumber", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.int) struct.originalPageNumber )
        ]


sourcePageDecoder : Json.Decode.Decoder SourcePage
sourcePageDecoder =
    Json.Decode.succeed SourcePage
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourcePdfSize" sizeInchesDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourceTrimBox" (Json.Decode.nullable pdfBoxDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "previewBox" (Json.Decode.nullable pdfBoxDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "physicalSizeAssumed" Json.Decode.bool))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "filename" (Json.Decode.nullable Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "originalPageNumber" (Json.Decode.nullable Json.Decode.int)))


type alias PageOverride =
    { pageNumber : Int
    , finishedCutSize : Maybe SizeInches
    , artworkFit : Maybe ArtworkFit
    }


pageOverrideEncoder : PageOverride -> Json.Encode.Value
pageOverrideEncoder struct =
    Json.Encode.object
        [ ( "pageNumber", Json.Encode.int struct.pageNumber )
        , ( "finishedCutSize", (Maybe.withDefault Json.Encode.null << Maybe.map sizeInchesEncoder) struct.finishedCutSize )
        , ( "artworkFit", (Maybe.withDefault Json.Encode.null << Maybe.map artworkFitEncoder) struct.artworkFit )
        ]


pageOverrideDecoder : Json.Decode.Decoder PageOverride
pageOverrideDecoder =
    Json.Decode.succeed PageOverride
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "pageNumber" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "finishedCutSize" (Json.Decode.nullable sizeInchesDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "artworkFit" (Json.Decode.nullable artworkFitDecoder)))


type alias PlanRect =
    { x : Float
    , y : Float
    , width : Float
    , height : Float
    }


planRectEncoder : PlanRect -> Json.Encode.Value
planRectEncoder struct =
    Json.Encode.object
        [ ( "x", Json.Encode.float struct.x )
        , ( "y", Json.Encode.float struct.y )
        , ( "width", Json.Encode.float struct.width )
        , ( "height", Json.Encode.float struct.height )
        ]


planRectDecoder : Json.Decode.Decoder PlanRect
planRectDecoder =
    Json.Decode.succeed PlanRect
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "x" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "y" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "width" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "height" Json.Decode.float))


type alias PagePlan =
    { positionTravel : CropPosition
    , pageNumber : Int
    , sourcePdfSize : SizeInches
    , previewBox : Maybe PdfBox
    , finishedCutSize : SizeInches
    , bleedAmount : Float
    , artwork : PlanRect
    }


pagePlanEncoder : PagePlan -> Json.Encode.Value
pagePlanEncoder struct =
    Json.Encode.object
        [ ( "positionTravel", cropPositionEncoder struct.positionTravel )
        , ( "pageNumber", Json.Encode.int struct.pageNumber )
        , ( "sourcePdfSize", sizeInchesEncoder struct.sourcePdfSize )
        , ( "previewBox", (Maybe.withDefault Json.Encode.null << Maybe.map pdfBoxEncoder) struct.previewBox )
        , ( "finishedCutSize", sizeInchesEncoder struct.finishedCutSize )
        , ( "bleedAmount", Json.Encode.float struct.bleedAmount )
        , ( "artwork", planRectEncoder struct.artwork )
        ]


pagePlanDecoder : Json.Decode.Decoder PagePlan
pagePlanDecoder =
    Json.Decode.succeed PagePlan
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "positionTravel" cropPositionDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "pageNumber" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourcePdfSize" sizeInchesDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "previewBox" (Json.Decode.nullable pdfBoxDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "finishedCutSize" sizeInchesDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "bleedAmount" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "artwork" planRectDecoder))


type Sides
    = SidesSingle
    | SidesDouble


sidesEncoder : Sides -> Json.Encode.Value
sidesEncoder enum =
    case enum of
        SidesSingle ->
            Json.Encode.string "single"

        SidesDouble ->
            Json.Encode.string "double"


sidesDecoder : Json.Decode.Decoder Sides
sidesDecoder =
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "single" ->
                            Json.Decode.succeed SidesSingle

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "double" ->
                            Json.Decode.succeed SidesDouble

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]


type LayoutMode
    = LayoutModeAuto
    | LayoutModeMaxPieces
    | LayoutModeManual


layoutModeEncoder : LayoutMode -> Json.Encode.Value
layoutModeEncoder enum =
    case enum of
        LayoutModeAuto ->
            Json.Encode.string "auto"

        LayoutModeMaxPieces ->
            Json.Encode.string "maxPieces"

        LayoutModeManual ->
            Json.Encode.string "manual"


layoutModeDecoder : Json.Decode.Decoder LayoutMode
layoutModeDecoder =
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "auto" ->
                            Json.Decode.succeed LayoutModeAuto

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "maxPieces" ->
                            Json.Decode.succeed LayoutModeMaxPieces

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "manual" ->
                            Json.Decode.succeed LayoutModeManual

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]


type BleedOption
    = BleedOptionUseAsIs
    | BleedOptionScaleToBleed
    | BleedOptionFitInside


bleedOptionEncoder : BleedOption -> Json.Encode.Value
bleedOptionEncoder enum =
    case enum of
        BleedOptionUseAsIs ->
            Json.Encode.string "useAsIs"

        BleedOptionScaleToBleed ->
            Json.Encode.string "scaleToBleed"

        BleedOptionFitInside ->
            Json.Encode.string "fitInside"


bleedOptionDecoder : Json.Decode.Decoder BleedOption
bleedOptionDecoder =
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "useAsIs" ->
                            Json.Decode.succeed BleedOptionUseAsIs

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "scaleToBleed" ->
                            Json.Decode.succeed BleedOptionScaleToBleed

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "fitInside" ->
                            Json.Decode.succeed BleedOptionFitInside

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]


type BleedSource
    = BleedSourceNone
    | BleedSourceDetected
    | BleedSourceManual


bleedSourceEncoder : BleedSource -> Json.Encode.Value
bleedSourceEncoder enum =
    case enum of
        BleedSourceNone ->
            Json.Encode.string "none"

        BleedSourceDetected ->
            Json.Encode.string "detected"

        BleedSourceManual ->
            Json.Encode.string "manual"


bleedSourceDecoder : Json.Decode.Decoder BleedSource
bleedSourceDecoder =
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "none" ->
                            Json.Decode.succeed BleedSourceNone

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "detected" ->
                            Json.Decode.succeed BleedSourceDetected

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "manual" ->
                            Json.Decode.succeed BleedSourceManual

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]


type ImpositionMode
    = ImpositionModeRepeat
    | ImpositionModeUnique


impositionModeEncoder : ImpositionMode -> Json.Encode.Value
impositionModeEncoder enum =
    case enum of
        ImpositionModeRepeat ->
            Json.Encode.string "repeat"

        ImpositionModeUnique ->
            Json.Encode.string "unique"


impositionModeDecoder : Json.Decode.Decoder ImpositionMode
impositionModeDecoder =
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "repeat" ->
                            Json.Decode.succeed ImpositionModeRepeat

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "unique" ->
                            Json.Decode.succeed ImpositionModeUnique

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]


type DuplexFlipEdge
    = DuplexFlipEdgeLongEdge
    | DuplexFlipEdgeShortEdge


duplexFlipEdgeEncoder : DuplexFlipEdge -> Json.Encode.Value
duplexFlipEdgeEncoder enum =
    case enum of
        DuplexFlipEdgeLongEdge ->
            Json.Encode.string "longEdge"

        DuplexFlipEdgeShortEdge ->
            Json.Encode.string "shortEdge"


duplexFlipEdgeDecoder : Json.Decode.Decoder DuplexFlipEdge
duplexFlipEdgeDecoder =
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "longEdge" ->
                            Json.Decode.succeed DuplexFlipEdgeLongEdge

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "shortEdge" ->
                            Json.Decode.succeed DuplexFlipEdgeShortEdge

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]


type alias PdfBox =
    { left : Float
    , bottom : Float
    , right : Float
    , top : Float
    , width : Float
    , height : Float
    }


pdfBoxEncoder : PdfBox -> Json.Encode.Value
pdfBoxEncoder struct =
    Json.Encode.object
        [ ( "left", Json.Encode.float struct.left )
        , ( "bottom", Json.Encode.float struct.bottom )
        , ( "right", Json.Encode.float struct.right )
        , ( "top", Json.Encode.float struct.top )
        , ( "width", Json.Encode.float struct.width )
        , ( "height", Json.Encode.float struct.height )
        ]


pdfBoxDecoder : Json.Decode.Decoder PdfBox
pdfBoxDecoder =
    Json.Decode.succeed PdfBox
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "left" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "bottom" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "right" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "top" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "width" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "height" Json.Decode.float))


type alias BleedDetection =
    { detected : Bool
    , amountPerSide : Float
    , horizontal : Float
    , vertical : Float
    , notes : List String
    }


bleedDetectionEncoder : BleedDetection -> Json.Encode.Value
bleedDetectionEncoder struct =
    Json.Encode.object
        [ ( "detected", Json.Encode.bool struct.detected )
        , ( "amountPerSide", Json.Encode.float struct.amountPerSide )
        , ( "horizontal", Json.Encode.float struct.horizontal )
        , ( "vertical", Json.Encode.float struct.vertical )
        , ( "notes", Json.Encode.list Json.Encode.string struct.notes )
        ]


bleedDetectionDecoder : Json.Decode.Decoder BleedDetection
bleedDetectionDecoder =
    Json.Decode.succeed BleedDetection
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "detected" Json.Decode.bool))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "amountPerSide" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "horizontal" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "vertical" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "notes" (Json.Decode.list Json.Decode.string)))


type ProductionWarningKind
    = ProductionWarningKindGeneral


productionWarningKindEncoder : ProductionWarningKind -> Json.Encode.Value
productionWarningKindEncoder enum =
    case enum of
        ProductionWarningKindGeneral ->
            Json.Encode.string "general"


productionWarningKindDecoder : Json.Decode.Decoder ProductionWarningKind
productionWarningKindDecoder =
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "general" ->
                            Json.Decode.succeed ProductionWarningKindGeneral

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]


type alias ProductionWarning =
    { kind : ProductionWarningKind
    , problem : String
    , impact : String
    , fix : String
    }


productionWarningEncoder : ProductionWarning -> Json.Encode.Value
productionWarningEncoder struct =
    Json.Encode.object
        [ ( "kind", productionWarningKindEncoder struct.kind )
        , ( "problem", Json.Encode.string struct.problem )
        , ( "impact", Json.Encode.string struct.impact )
        , ( "fix", Json.Encode.string struct.fix )
        ]


productionWarningDecoder : Json.Decode.Decoder ProductionWarning
productionWarningDecoder =
    Json.Decode.succeed ProductionWarning
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "kind" productionWarningKindDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "problem" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "impact" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "fix" Json.Decode.string))


type alias PdfAnalysis =
    { sourcePages : List SourcePage
    , filename : String
    , pageCount : Int
    , sourcePdfSize : SizeInches
    , orientation : Orientation
    , mediaBox : Maybe PdfBox
    , cropBox : Maybe PdfBox
    , bleedBox : Maybe PdfBox
    , trimBox : Maybe PdfBox
    , likelyBleed : BleedDetection
    , matchedPresetId : Maybe String
    , suggestedFinishedCutSize : Maybe SizeInches
    , appearsDuplex : Bool
    , orientationAdjustedPages : Int
    , warnings : List ProductionWarning
    }


pdfAnalysisEncoder : PdfAnalysis -> Json.Encode.Value
pdfAnalysisEncoder struct =
    Json.Encode.object
        [ ( "sourcePages", Json.Encode.list sourcePageEncoder struct.sourcePages )
        , ( "filename", Json.Encode.string struct.filename )
        , ( "pageCount", Json.Encode.int struct.pageCount )
        , ( "sourcePdfSize", sizeInchesEncoder struct.sourcePdfSize )
        , ( "orientation", orientationEncoder struct.orientation )
        , ( "mediaBox", (Maybe.withDefault Json.Encode.null << Maybe.map pdfBoxEncoder) struct.mediaBox )
        , ( "cropBox", (Maybe.withDefault Json.Encode.null << Maybe.map pdfBoxEncoder) struct.cropBox )
        , ( "bleedBox", (Maybe.withDefault Json.Encode.null << Maybe.map pdfBoxEncoder) struct.bleedBox )
        , ( "trimBox", (Maybe.withDefault Json.Encode.null << Maybe.map pdfBoxEncoder) struct.trimBox )
        , ( "likelyBleed", bleedDetectionEncoder struct.likelyBleed )
        , ( "matchedPresetId", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.string) struct.matchedPresetId )
        , ( "suggestedFinishedCutSize", (Maybe.withDefault Json.Encode.null << Maybe.map sizeInchesEncoder) struct.suggestedFinishedCutSize )
        , ( "appearsDuplex", Json.Encode.bool struct.appearsDuplex )
        , ( "orientationAdjustedPages", Json.Encode.int struct.orientationAdjustedPages )
        , ( "warnings", Json.Encode.list productionWarningEncoder struct.warnings )
        ]


pdfAnalysisDecoder : Json.Decode.Decoder PdfAnalysis
pdfAnalysisDecoder =
    Json.Decode.succeed PdfAnalysis
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourcePages" (Json.Decode.list sourcePageDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "filename" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "pageCount" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourcePdfSize" sizeInchesDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "orientation" orientationDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "mediaBox" (Json.Decode.nullable pdfBoxDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "cropBox" (Json.Decode.nullable pdfBoxDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "bleedBox" (Json.Decode.nullable pdfBoxDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "trimBox" (Json.Decode.nullable pdfBoxDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "likelyBleed" bleedDetectionDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "matchedPresetId" (Json.Decode.nullable Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "suggestedFinishedCutSize" (Json.Decode.nullable sizeInchesDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "appearsDuplex" Json.Decode.bool))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "orientationAdjustedPages" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "warnings" (Json.Decode.list productionWarningDecoder)))


type alias LayoutRequest =
    { sourceId : Maybe String
    , sourcePages : List SourcePage
    , finishedSizeMode : FinishedSizeMode
    , artworkFit : Maybe ArtworkFit
    , pageOverrides : List PageOverride
    , sourcePdfSize : SizeInches
    , sourceTrimBox : Maybe PdfBox
    , sourcePageCount : Maybe Int
    , finishedCutSize : SizeInches
    , parentSheetSize : SizeInches
    , quantityRequested : Int
    , impositionMode : ImpositionMode
    , impressionQuantities : Maybe (List Int)
    , orientationPreference : OrientationPreference
    , sides : Sides
    , duplex : Maybe DuplexSettings
    , layoutMode : LayoutMode
    , bleedOption : BleedOption
    , sourceBleedOverride : Maybe Float
    , createdBleedAmount : Float
    , gutter : GuttersInches
    , manual : Maybe ManualLayout
    }


layoutRequestEncoder : LayoutRequest -> Json.Encode.Value
layoutRequestEncoder struct =
    Json.Encode.object
        [ ( "sourceId", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.string) struct.sourceId )
        , ( "sourcePages", Json.Encode.list sourcePageEncoder struct.sourcePages )
        , ( "finishedSizeMode", finishedSizeModeEncoder struct.finishedSizeMode )
        , ( "artworkFit", (Maybe.withDefault Json.Encode.null << Maybe.map artworkFitEncoder) struct.artworkFit )
        , ( "pageOverrides", Json.Encode.list pageOverrideEncoder struct.pageOverrides )
        , ( "sourcePdfSize", sizeInchesEncoder struct.sourcePdfSize )
        , ( "sourceTrimBox", (Maybe.withDefault Json.Encode.null << Maybe.map pdfBoxEncoder) struct.sourceTrimBox )
        , ( "sourcePageCount", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.int) struct.sourcePageCount )
        , ( "finishedCutSize", sizeInchesEncoder struct.finishedCutSize )
        , ( "parentSheetSize", sizeInchesEncoder struct.parentSheetSize )
        , ( "quantityRequested", Json.Encode.int struct.quantityRequested )
        , ( "impositionMode", impositionModeEncoder struct.impositionMode )
        , ( "impressionQuantities", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.list Json.Encode.int)) struct.impressionQuantities )
        , ( "orientationPreference", orientationPreferenceEncoder struct.orientationPreference )
        , ( "sides", sidesEncoder struct.sides )
        , ( "duplex", (Maybe.withDefault Json.Encode.null << Maybe.map duplexSettingsEncoder) struct.duplex )
        , ( "layoutMode", layoutModeEncoder struct.layoutMode )
        , ( "bleedOption", bleedOptionEncoder struct.bleedOption )
        , ( "sourceBleedOverride", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.float) struct.sourceBleedOverride )
        , ( "createdBleedAmount", Json.Encode.float struct.createdBleedAmount )
        , ( "gutter", guttersInchesEncoder struct.gutter )
        , ( "manual", (Maybe.withDefault Json.Encode.null << Maybe.map manualLayoutEncoder) struct.manual )
        ]


layoutRequestDecoder : Json.Decode.Decoder LayoutRequest
layoutRequestDecoder =
    Json.Decode.succeed LayoutRequest
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourceId" (Json.Decode.nullable Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourcePages" (Json.Decode.list sourcePageDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "finishedSizeMode" finishedSizeModeDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "artworkFit" (Json.Decode.nullable artworkFitDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "pageOverrides" (Json.Decode.list pageOverrideDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourcePdfSize" sizeInchesDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourceTrimBox" (Json.Decode.nullable pdfBoxDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourcePageCount" (Json.Decode.nullable Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "finishedCutSize" sizeInchesDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "parentSheetSize" sizeInchesDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "quantityRequested" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "impositionMode" impositionModeDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "impressionQuantities" (Json.Decode.nullable (Json.Decode.list Json.Decode.int))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "orientationPreference" orientationPreferenceDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sides" sidesDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "duplex" (Json.Decode.nullable duplexSettingsDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "layoutMode" layoutModeDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "bleedOption" bleedOptionDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourceBleedOverride" (Json.Decode.nullable Json.Decode.float)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "createdBleedAmount" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "gutter" guttersInchesDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "manual" (Json.Decode.nullable manualLayoutDecoder)))


type alias ManualLayout =
    { rows : Int
    , columns : Int
    , rotationDegrees : Int
    , margins : Maybe MarginsInches
    }


manualLayoutEncoder : ManualLayout -> Json.Encode.Value
manualLayoutEncoder struct =
    Json.Encode.object
        [ ( "rows", Json.Encode.int struct.rows )
        , ( "columns", Json.Encode.int struct.columns )
        , ( "rotationDegrees", Json.Encode.int struct.rotationDegrees )
        , ( "margins", (Maybe.withDefault Json.Encode.null << Maybe.map marginsInchesEncoder) struct.margins )
        ]


manualLayoutDecoder : Json.Decode.Decoder ManualLayout
manualLayoutDecoder =
    Json.Decode.succeed ManualLayout
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "rows" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "columns" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "rotationDegrees" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "margins" (Json.Decode.nullable marginsInchesDecoder)))


type alias LayoutResult =
    { sourceBleedOverride : Maybe Float
    , pagePlans : List PagePlan
    , sourcePdfSize : SizeInches
    , sourceTrimBox : Maybe PdfBox
    , sourcePageCount : Maybe Int
    , finishedCutSize : SizeInches
    , parentSheetSize : SizeInches
    , quantityRequested : Int
    , impositionMode : ImpositionMode
    , impressionQuantities : Maybe (List Int)
    , orientationPreference : OrientationPreference
    , impressionsRequested : Int
    , piecesPerSheet : Int
    , sheetsRequired : Int
    , totalPiecesProduced : Int
    , extraPiecesProduced : Int
    , unusedPositions : Int
    , wastePercent : Float
    , rotationDegrees : Int
    , rows : Int
    , columns : Int
    , margins : MarginsInches
    , gutters : GuttersInches
    , placements : List PiecePlacement
    , duplex : Maybe DuplexSettings
    , bleed : BleedSettings
    , createdBleedAmount : Float
    , warnings : List ProductionWarning
    }


layoutResultEncoder : LayoutResult -> Json.Encode.Value
layoutResultEncoder struct =
    Json.Encode.object
        [ ( "sourceBleedOverride", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.float) struct.sourceBleedOverride )
        , ( "pagePlans", Json.Encode.list pagePlanEncoder struct.pagePlans )
        , ( "sourcePdfSize", sizeInchesEncoder struct.sourcePdfSize )
        , ( "sourceTrimBox", (Maybe.withDefault Json.Encode.null << Maybe.map pdfBoxEncoder) struct.sourceTrimBox )
        , ( "sourcePageCount", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.int) struct.sourcePageCount )
        , ( "finishedCutSize", sizeInchesEncoder struct.finishedCutSize )
        , ( "parentSheetSize", sizeInchesEncoder struct.parentSheetSize )
        , ( "quantityRequested", Json.Encode.int struct.quantityRequested )
        , ( "impositionMode", impositionModeEncoder struct.impositionMode )
        , ( "impressionQuantities", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.list Json.Encode.int)) struct.impressionQuantities )
        , ( "orientationPreference", orientationPreferenceEncoder struct.orientationPreference )
        , ( "impressionsRequested", Json.Encode.int struct.impressionsRequested )
        , ( "piecesPerSheet", Json.Encode.int struct.piecesPerSheet )
        , ( "sheetsRequired", Json.Encode.int struct.sheetsRequired )
        , ( "totalPiecesProduced", Json.Encode.int struct.totalPiecesProduced )
        , ( "extraPiecesProduced", Json.Encode.int struct.extraPiecesProduced )
        , ( "unusedPositions", Json.Encode.int struct.unusedPositions )
        , ( "wastePercent", Json.Encode.float struct.wastePercent )
        , ( "rotationDegrees", Json.Encode.int struct.rotationDegrees )
        , ( "rows", Json.Encode.int struct.rows )
        , ( "columns", Json.Encode.int struct.columns )
        , ( "margins", marginsInchesEncoder struct.margins )
        , ( "gutters", guttersInchesEncoder struct.gutters )
        , ( "placements", Json.Encode.list piecePlacementEncoder struct.placements )
        , ( "duplex", (Maybe.withDefault Json.Encode.null << Maybe.map duplexSettingsEncoder) struct.duplex )
        , ( "bleed", bleedSettingsEncoder struct.bleed )
        , ( "createdBleedAmount", Json.Encode.float struct.createdBleedAmount )
        , ( "warnings", Json.Encode.list productionWarningEncoder struct.warnings )
        ]


layoutResultDecoder : Json.Decode.Decoder LayoutResult
layoutResultDecoder =
    Json.Decode.succeed LayoutResult
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourceBleedOverride" (Json.Decode.nullable Json.Decode.float)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "pagePlans" (Json.Decode.list pagePlanDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourcePdfSize" sizeInchesDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourceTrimBox" (Json.Decode.nullable pdfBoxDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourcePageCount" (Json.Decode.nullable Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "finishedCutSize" sizeInchesDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "parentSheetSize" sizeInchesDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "quantityRequested" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "impositionMode" impositionModeDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "impressionQuantities" (Json.Decode.nullable (Json.Decode.list Json.Decode.int))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "orientationPreference" orientationPreferenceDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "impressionsRequested" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "piecesPerSheet" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sheetsRequired" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "totalPiecesProduced" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "extraPiecesProduced" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "unusedPositions" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "wastePercent" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "rotationDegrees" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "rows" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "columns" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "margins" marginsInchesDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "gutters" guttersInchesDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "placements" (Json.Decode.list piecePlacementDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "duplex" (Json.Decode.nullable duplexSettingsDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "bleed" bleedSettingsDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "createdBleedAmount" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "warnings" (Json.Decode.list productionWarningDecoder)))


type alias RecentGangUpJob =
    { id : String
    , name : String
    , sourceFilename : Maybe String
    , savedAt : String
    , request : LayoutRequest
    , layoutSummary : Maybe RecentGangUpLayoutSummary
    }


recentGangUpJobEncoder : RecentGangUpJob -> Json.Encode.Value
recentGangUpJobEncoder struct =
    Json.Encode.object
        [ ( "id", Json.Encode.string struct.id )
        , ( "name", Json.Encode.string struct.name )
        , ( "sourceFilename", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.string) struct.sourceFilename )
        , ( "savedAt", Json.Encode.string struct.savedAt )
        , ( "request", layoutRequestEncoder struct.request )
        , ( "layoutSummary", (Maybe.withDefault Json.Encode.null << Maybe.map recentGangUpLayoutSummaryEncoder) struct.layoutSummary )
        ]


recentGangUpJobDecoder : Json.Decode.Decoder RecentGangUpJob
recentGangUpJobDecoder =
    Json.Decode.succeed RecentGangUpJob
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourceFilename" (Json.Decode.nullable Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "savedAt" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "request" layoutRequestDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "layoutSummary" (Json.Decode.nullable recentGangUpLayoutSummaryDecoder)))


type alias RecentGangUpJobInput =
    { name : Maybe String
    , sourceFilename : Maybe String
    , request : LayoutRequest
    , layoutSummary : Maybe RecentGangUpLayoutSummary
    }


recentGangUpJobInputEncoder : RecentGangUpJobInput -> Json.Encode.Value
recentGangUpJobInputEncoder struct =
    Json.Encode.object
        [ ( "name", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.string) struct.name )
        , ( "sourceFilename", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.string) struct.sourceFilename )
        , ( "request", layoutRequestEncoder struct.request )
        , ( "layoutSummary", (Maybe.withDefault Json.Encode.null << Maybe.map recentGangUpLayoutSummaryEncoder) struct.layoutSummary )
        ]


recentGangUpJobInputDecoder : Json.Decode.Decoder RecentGangUpJobInput
recentGangUpJobInputDecoder =
    Json.Decode.succeed RecentGangUpJobInput
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" (Json.Decode.nullable Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourceFilename" (Json.Decode.nullable Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "request" layoutRequestDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "layoutSummary" (Json.Decode.nullable recentGangUpLayoutSummaryDecoder)))


type GangUpExportType
    = GangUpExportTypeCleanPdf
    | GangUpExportTypeLegacyDuploCutPlan


gangUpExportTypeEncoder : GangUpExportType -> Json.Encode.Value
gangUpExportTypeEncoder enum =
    case enum of
        GangUpExportTypeCleanPdf ->
            Json.Encode.string "cleanPdf"

        GangUpExportTypeLegacyDuploCutPlan ->
            Json.Encode.string "duploCutPlan"


gangUpExportTypeDecoder : Json.Decode.Decoder GangUpExportType
gangUpExportTypeDecoder =
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "cleanPdf" ->
                            Json.Decode.succeed GangUpExportTypeCleanPdf

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "duploCutPlan" ->
                            Json.Decode.succeed GangUpExportTypeLegacyDuploCutPlan

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]


type OutputPreference
    = OutputPreferenceCleanPdf


outputPreferenceEncoder : OutputPreference -> Json.Encode.Value
outputPreferenceEncoder enum =
    case enum of
        OutputPreferenceCleanPdf ->
            Json.Encode.string "cleanPdf"


outputPreferenceDecoder : Json.Decode.Decoder OutputPreference
outputPreferenceDecoder =
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "cleanPdf" ->
                            Json.Decode.succeed OutputPreferenceCleanPdf

                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]


type alias GangUpExportRecord =
    { id : String
    , name : String
    , sourceFilename : Maybe String
    , exportedAt : String
    , outputType : GangUpExportType
    , outputFilename : String
    , hasStoredFile : Bool
    , request : LayoutRequest
    , layoutSummary : Maybe RecentGangUpLayoutSummary
    }


gangUpExportRecordEncoder : GangUpExportRecord -> Json.Encode.Value
gangUpExportRecordEncoder struct =
    Json.Encode.object
        [ ( "id", Json.Encode.string struct.id )
        , ( "name", Json.Encode.string struct.name )
        , ( "sourceFilename", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.string) struct.sourceFilename )
        , ( "exportedAt", Json.Encode.string struct.exportedAt )
        , ( "outputType", gangUpExportTypeEncoder struct.outputType )
        , ( "outputFilename", Json.Encode.string struct.outputFilename )
        , ( "hasStoredFile", Json.Encode.bool struct.hasStoredFile )
        , ( "request", layoutRequestEncoder struct.request )
        , ( "layoutSummary", (Maybe.withDefault Json.Encode.null << Maybe.map recentGangUpLayoutSummaryEncoder) struct.layoutSummary )
        ]


gangUpExportRecordDecoder : Json.Decode.Decoder GangUpExportRecord
gangUpExportRecordDecoder =
    Json.Decode.succeed GangUpExportRecord
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourceFilename" (Json.Decode.nullable Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "exportedAt" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "outputType" gangUpExportTypeDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "outputFilename" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "hasStoredFile" Json.Decode.bool))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "request" layoutRequestDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "layoutSummary" (Json.Decode.nullable recentGangUpLayoutSummaryDecoder)))


type alias GangUpExportRecordInput =
    { name : Maybe String
    , sourceFilename : Maybe String
    , outputType : GangUpExportType
    , outputFilename : String
    , storedFile : Maybe GangUpStoredExportFileInput
    , request : LayoutRequest
    , layoutSummary : Maybe RecentGangUpLayoutSummary
    }


gangUpExportRecordInputEncoder : GangUpExportRecordInput -> Json.Encode.Value
gangUpExportRecordInputEncoder struct =
    Json.Encode.object
        [ ( "name", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.string) struct.name )
        , ( "sourceFilename", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.string) struct.sourceFilename )
        , ( "outputType", gangUpExportTypeEncoder struct.outputType )
        , ( "outputFilename", Json.Encode.string struct.outputFilename )
        , ( "storedFile", (Maybe.withDefault Json.Encode.null << Maybe.map gangUpStoredExportFileInputEncoder) struct.storedFile )
        , ( "request", layoutRequestEncoder struct.request )
        , ( "layoutSummary", (Maybe.withDefault Json.Encode.null << Maybe.map recentGangUpLayoutSummaryEncoder) struct.layoutSummary )
        ]


gangUpExportRecordInputDecoder : Json.Decode.Decoder GangUpExportRecordInput
gangUpExportRecordInputDecoder =
    Json.Decode.succeed GangUpExportRecordInput
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" (Json.Decode.nullable Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourceFilename" (Json.Decode.nullable Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "outputType" gangUpExportTypeDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "outputFilename" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "storedFile" (Json.Decode.nullable gangUpStoredExportFileInputDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "request" layoutRequestDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "layoutSummary" (Json.Decode.nullable recentGangUpLayoutSummaryDecoder)))


type alias GangUpStoredExportFileInput =
    { contentType : String
    , base64 : String
    }


gangUpStoredExportFileInputEncoder : GangUpStoredExportFileInput -> Json.Encode.Value
gangUpStoredExportFileInputEncoder struct =
    Json.Encode.object
        [ ( "contentType", Json.Encode.string struct.contentType )
        , ( "base64", Json.Encode.string struct.base64 )
        ]


gangUpStoredExportFileInputDecoder : Json.Decode.Decoder GangUpStoredExportFileInput
gangUpStoredExportFileInputDecoder =
    Json.Decode.succeed GangUpStoredExportFileInput
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "contentType" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "base64" Json.Decode.string))


type alias RecentGangUpLayoutSummary =
    { piecesPerSheet : Int
    , sheetsRequired : Int
    , totalPiecesProduced : Int
    , extraPiecesProduced : Int
    }


recentGangUpLayoutSummaryEncoder : RecentGangUpLayoutSummary -> Json.Encode.Value
recentGangUpLayoutSummaryEncoder struct =
    Json.Encode.object
        [ ( "piecesPerSheet", Json.Encode.int struct.piecesPerSheet )
        , ( "sheetsRequired", Json.Encode.int struct.sheetsRequired )
        , ( "totalPiecesProduced", Json.Encode.int struct.totalPiecesProduced )
        , ( "extraPiecesProduced", Json.Encode.int struct.extraPiecesProduced )
        ]


recentGangUpLayoutSummaryDecoder : Json.Decode.Decoder RecentGangUpLayoutSummary
recentGangUpLayoutSummaryDecoder =
    Json.Decode.succeed RecentGangUpLayoutSummary
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "piecesPerSheet" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sheetsRequired" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "totalPiecesProduced" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "extraPiecesProduced" Json.Decode.int))


type alias PiecePlacement =
    { index : Int
    , row : Int
    , column : Int
    , x : Float
    , y : Float
    , width : Float
    , height : Float
    , finishedX : Float
    , finishedY : Float
    , finishedWidth : Float
    , finishedHeight : Float
    }


piecePlacementEncoder : PiecePlacement -> Json.Encode.Value
piecePlacementEncoder struct =
    Json.Encode.object
        [ ( "index", Json.Encode.int struct.index )
        , ( "row", Json.Encode.int struct.row )
        , ( "column", Json.Encode.int struct.column )
        , ( "x", Json.Encode.float struct.x )
        , ( "y", Json.Encode.float struct.y )
        , ( "width", Json.Encode.float struct.width )
        , ( "height", Json.Encode.float struct.height )
        , ( "finishedX", Json.Encode.float struct.finishedX )
        , ( "finishedY", Json.Encode.float struct.finishedY )
        , ( "finishedWidth", Json.Encode.float struct.finishedWidth )
        , ( "finishedHeight", Json.Encode.float struct.finishedHeight )
        ]


piecePlacementDecoder : Json.Decode.Decoder PiecePlacement
piecePlacementDecoder =
    Json.Decode.succeed PiecePlacement
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "index" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "row" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "column" Json.Decode.int))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "x" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "y" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "width" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "height" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "finishedX" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "finishedY" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "finishedWidth" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "finishedHeight" Json.Decode.float))


type alias DuplexSettings =
    { flipEdge : DuplexFlipEdge
    , rotateBack180 : Bool
    , backAlignment : String
    }


duplexSettingsEncoder : DuplexSettings -> Json.Encode.Value
duplexSettingsEncoder struct =
    Json.Encode.object
        [ ( "flipEdge", duplexFlipEdgeEncoder struct.flipEdge )
        , ( "rotateBack180", Json.Encode.bool struct.rotateBack180 )
        ]


duplexSettingsDecoder : Json.Decode.Decoder DuplexSettings
duplexSettingsDecoder =
    Json.Decode.succeed DuplexSettings
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "flipEdge" duplexFlipEdgeDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "rotateBack180" Json.Decode.bool))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "backAlignment" Json.Decode.string))


type alias BleedSettings =
    { option : BleedOption
    , detectedAmountPerSide : Float
    , effectiveAmountPerSide : Float
    , source : BleedSource
    , sourceLargerThanCut : Bool
    }


bleedSettingsEncoder : BleedSettings -> Json.Encode.Value
bleedSettingsEncoder struct =
    Json.Encode.object
        [ ( "option", bleedOptionEncoder struct.option )
        , ( "detectedAmountPerSide", Json.Encode.float struct.detectedAmountPerSide )
        , ( "effectiveAmountPerSide", Json.Encode.float struct.effectiveAmountPerSide )
        , ( "source", bleedSourceEncoder struct.source )
        , ( "sourceLargerThanCut", Json.Encode.bool struct.sourceLargerThanCut )
        ]


bleedSettingsDecoder : Json.Decode.Decoder BleedSettings
bleedSettingsDecoder =
    Json.Decode.succeed BleedSettings
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "option" bleedOptionDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "detectedAmountPerSide" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "effectiveAmountPerSide" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "source" bleedSourceDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourceLargerThanCut" Json.Decode.bool))


type alias GangUpPreset =
    { impositionMode : ImpositionMode
    , finishedSizeMode : FinishedSizeMode
    , artworkFit : Maybe ArtworkFit
    , sourceBleedOverride : Maybe Float
    , id : String
    , name : String
    , finishedCutSize : SizeInches
    , parentSheetSize : SizeInches
    , bleedHandling : BleedOption
    , createdBleedAmount : Float
    , gutter : GuttersInches
    , orientationPreference : OrientationPreference
    , sides : Sides
    , layoutPreference : LayoutMode
    , manual : Maybe ManualLayout
    , duplex : Maybe DuplexSettings
    , outputPreference : OutputPreference
    , builtIn : Bool
    }


gangUpPresetEncoder : GangUpPreset -> Json.Encode.Value
gangUpPresetEncoder struct =
    Json.Encode.object
        [ ( "impositionMode", impositionModeEncoder struct.impositionMode )
        , ( "finishedSizeMode", finishedSizeModeEncoder struct.finishedSizeMode )
        , ( "artworkFit", (Maybe.withDefault Json.Encode.null << Maybe.map artworkFitEncoder) struct.artworkFit )
        , ( "sourceBleedOverride", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.float) struct.sourceBleedOverride )
        , ( "id", Json.Encode.string struct.id )
        , ( "name", Json.Encode.string struct.name )
        , ( "finishedCutSize", sizeInchesEncoder struct.finishedCutSize )
        , ( "parentSheetSize", sizeInchesEncoder struct.parentSheetSize )
        , ( "bleedHandling", bleedOptionEncoder struct.bleedHandling )
        , ( "createdBleedAmount", Json.Encode.float struct.createdBleedAmount )
        , ( "gutter", guttersInchesEncoder struct.gutter )
        , ( "orientationPreference", orientationPreferenceEncoder struct.orientationPreference )
        , ( "sides", sidesEncoder struct.sides )
        , ( "layoutPreference", layoutModeEncoder struct.layoutPreference )
        , ( "manual", (Maybe.withDefault Json.Encode.null << Maybe.map manualLayoutEncoder) struct.manual )
        , ( "duplex", (Maybe.withDefault Json.Encode.null << Maybe.map duplexSettingsEncoder) struct.duplex )
        , ( "outputPreference", outputPreferenceEncoder struct.outputPreference )
        , ( "builtIn", Json.Encode.bool struct.builtIn )
        ]


gangUpPresetDecoder : Json.Decode.Decoder GangUpPreset
gangUpPresetDecoder =
    Json.Decode.succeed GangUpPreset
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "impositionMode" impositionModeDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "finishedSizeMode" finishedSizeModeDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "artworkFit" (Json.Decode.nullable artworkFitDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourceBleedOverride" (Json.Decode.nullable Json.Decode.float)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "finishedCutSize" sizeInchesDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "parentSheetSize" sizeInchesDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "bleedHandling" bleedOptionDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "createdBleedAmount" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "gutter" guttersInchesDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "orientationPreference" orientationPreferenceDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sides" sidesDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "layoutPreference" layoutModeDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "manual" (Json.Decode.nullable manualLayoutDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "duplex" (Json.Decode.nullable duplexSettingsDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "outputPreference" outputPreferenceDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "builtIn" Json.Decode.bool))


type alias PresetInput =
    { impositionMode : ImpositionMode
    , finishedSizeMode : FinishedSizeMode
    , artworkFit : Maybe ArtworkFit
    , sourceBleedOverride : Maybe Float
    , id : Maybe String
    , name : String
    , finishedCutSize : SizeInches
    , parentSheetSize : SizeInches
    , bleedHandling : BleedOption
    , createdBleedAmount : Float
    , gutter : GuttersInches
    , orientationPreference : OrientationPreference
    , sides : Sides
    , layoutPreference : LayoutMode
    , manual : Maybe ManualLayout
    , duplex : Maybe DuplexSettings
    , outputPreference : Maybe OutputPreference
    }


presetInputEncoder : PresetInput -> Json.Encode.Value
presetInputEncoder struct =
    Json.Encode.object
        [ ( "impositionMode", impositionModeEncoder struct.impositionMode )
        , ( "finishedSizeMode", finishedSizeModeEncoder struct.finishedSizeMode )
        , ( "artworkFit", (Maybe.withDefault Json.Encode.null << Maybe.map artworkFitEncoder) struct.artworkFit )
        , ( "sourceBleedOverride", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.float) struct.sourceBleedOverride )
        , ( "id", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.string) struct.id )
        , ( "name", Json.Encode.string struct.name )
        , ( "finishedCutSize", sizeInchesEncoder struct.finishedCutSize )
        , ( "parentSheetSize", sizeInchesEncoder struct.parentSheetSize )
        , ( "bleedHandling", bleedOptionEncoder struct.bleedHandling )
        , ( "createdBleedAmount", Json.Encode.float struct.createdBleedAmount )
        , ( "gutter", guttersInchesEncoder struct.gutter )
        , ( "orientationPreference", orientationPreferenceEncoder struct.orientationPreference )
        , ( "sides", sidesEncoder struct.sides )
        , ( "layoutPreference", layoutModeEncoder struct.layoutPreference )
        , ( "manual", (Maybe.withDefault Json.Encode.null << Maybe.map manualLayoutEncoder) struct.manual )
        , ( "duplex", (Maybe.withDefault Json.Encode.null << Maybe.map duplexSettingsEncoder) struct.duplex )
        , ( "outputPreference", (Maybe.withDefault Json.Encode.null << Maybe.map outputPreferenceEncoder) struct.outputPreference )
        ]


presetInputDecoder : Json.Decode.Decoder PresetInput
presetInputDecoder =
    Json.Decode.succeed PresetInput
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "impositionMode" impositionModeDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "finishedSizeMode" finishedSizeModeDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "artworkFit" (Json.Decode.nullable artworkFitDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourceBleedOverride" (Json.Decode.nullable Json.Decode.float)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (Json.Decode.nullable Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "finishedCutSize" sizeInchesDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "parentSheetSize" sizeInchesDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "bleedHandling" bleedOptionDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "createdBleedAmount" Json.Decode.float))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "gutter" guttersInchesDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "orientationPreference" orientationPreferenceDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sides" sidesDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "layoutPreference" layoutModeDecoder))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "manual" (Json.Decode.nullable manualLayoutDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "duplex" (Json.Decode.nullable duplexSettingsDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "outputPreference" (Json.Decode.nullable outputPreferenceDecoder)))


type alias PreparedSourceResponse =
    { sourceId : String
    , analysis : PdfAnalysis
    }


preparedSourceResponseEncoder : PreparedSourceResponse -> Json.Encode.Value
preparedSourceResponseEncoder struct =
    Json.Encode.object
        [ ( "sourceId", Json.Encode.string struct.sourceId )
        , ( "analysis", pdfAnalysisEncoder struct.analysis )
        ]


preparedSourceResponseDecoder : Json.Decode.Decoder PreparedSourceResponse
preparedSourceResponseDecoder =
    Json.Decode.succeed PreparedSourceResponse
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourceId" Json.Decode.string))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "analysis" pdfAnalysisDecoder))


type alias PreviewBatchRequest =
    { pageNumbers : List Int
    , sourceBleedOverride : Maybe Float
    }


previewBatchRequestEncoder : PreviewBatchRequest -> Json.Encode.Value
previewBatchRequestEncoder struct =
    Json.Encode.object
        [ ( "pageNumbers", Json.Encode.list Json.Encode.int struct.pageNumbers )
        , ( "sourceBleedOverride", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.float) struct.sourceBleedOverride )
        ]


previewBatchRequestDecoder : Json.Decode.Decoder PreviewBatchRequest
previewBatchRequestDecoder =
    Json.Decode.succeed PreviewBatchRequest
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "pageNumbers" (Json.Decode.list Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "sourceBleedOverride" (Json.Decode.nullable Json.Decode.float)))
