//! Reproducible Elm wire types. Enabled only for development and CI generation.
#[allow(dead_code)]
mod wire {
    include!(concat!(env!("OUT_DIR"), "/elm_model.rs"));
}
use elm_rs::{Elm, ElmDecode, ElmEncode};
use wire::*;

fn definition<T: Elm + ElmEncode + ElmDecode>() -> String {
    let ty = T::elm_definition().unwrap_or_default();
    let mut code = format!(
        "{}\n{}\n{}\n",
        ty,
        T::encoder_definition().unwrap_or_default(),
        T::decoder_definition().unwrap_or_default()
    );
    // Elm constructors occupy one namespace. Prefix each unit enum's
    // constructors without changing Serde strings or Rust enum names.
    if ty.starts_with("type ") && !ty.starts_with("type alias ") {
        let name = ty.split_whitespace().nth(1).unwrap_or_default();
        let variants: Vec<_> = ty
            .lines()
            .filter_map(|line| {
                let line = line.trim();
                line.strip_prefix("= ")
                    .or_else(|| line.strip_prefix("| "))
                    .map(|v| v.trim().to_owned())
            })
            .collect();
        let mut out = String::new();
        let mut word = String::new();
        let mut quoted = false;
        for ch in code.chars().chain(std::iter::once('\n')) {
            if ch.is_alphanumeric() || ch == '_' {
                word.push(ch);
            } else {
                if !quoted && variants.contains(&word) {
                    out.push_str(name);
                }
                out.push_str(&word);
                word.clear();
                out.push(ch);
                if ch == '"' {
                    quoted = !quoted;
                }
            }
        }
        code = out;
    }
    // Serde ignores this output-only metadata on request deserialization.
    code = code.replace(
        "        , ( \"backAlignment\", (Json.Encode.string) struct.backAlignment )\n",
        "",
    );
    code
}

/// Generates types and codecs directly from the backend's wire models.
pub fn generate() -> String {
    let mut code = String::from("-- Generated by cargo run --features elm-codegen --bin generate-elm. Do not edit.\nmodule Api.Generated exposing (..)\n\nimport Json.Decode\nimport Json.Encode\n\n");
    macro_rules! add { ($($t:ty),* $(,)?) => { $(code.push_str(&definition::<$t>());)* }; }
    add!(
        SizeInches,
        MarginsInches,
        GuttersInches,
        Orientation,
        OrientationPreference,
        FinishedSizeMode,
        ArtworkFitMode,
        CropPosition,
        ArtworkFit,
        SourcePage,
        PageOverride,
        PlanRect,
        PagePlan,
        Sides,
        LayoutMode,
        BleedOption,
        BleedSource,
        ImpositionMode,
        DuplexFlipEdge,
        PdfBox,
        BleedDetection,
        ProductionWarningKind,
        ProductionWarning,
        PdfAnalysis,
        LayoutRequest,
        ManualLayout,
        LayoutResult,
        RecentGangUpJob,
        RecentGangUpJobInput,
        GangUpExportType,
        OutputPreference,
        GangUpExportRecord,
        GangUpExportRecordInput,
        GangUpStoredExportFileInput,
        RecentGangUpLayoutSummary,
        PiecePlacement,
        DuplexSettings,
        BleedSettings,
        GangUpPreset,
        PresetInput,
        PreparedSourceResponse,
        PreviewBatchRequest
    );
    code
}

/// Produces Elm contract fixtures using production Rust serialization and layout.
pub fn contract_fixtures() -> crate::AppResult<String> {
    use crate::imposition::model as actual;
    use serde_json::{json, Value};
    let mut cases: Vec<(&str, Value)> = Vec::new();
    macro_rules! add {
        ($name:literal, $value:expr) => {
            cases.push((
                $name,
                serde_json::to_value($value)
                    .map_err(|e| crate::AppError::internal_cause("contract serialization", e))?,
            ));
        };
    }
    macro_rules! variants { ($name:literal, $ty:ident, $($variant:ident),+) => { $(add!($name, actual::$ty::$variant);)+ }; }
    variants!("Orientation", Orientation, Portrait, Landscape, Square);
    variants!(
        "OrientationPreference",
        OrientationPreference,
        Auto,
        Portrait,
        Landscape,
        Upright,
        QuarterTurn
    );
    variants!("FinishedSizeMode", FinishedSizeMode, Common, Original);
    variants!("ArtworkFitMode", ArtworkFitMode, Contain, Cover, Stretch);
    variants!("Sides", Sides, Single, Double);
    variants!("LayoutMode", LayoutMode, Auto, MaxPieces, Manual);
    variants!("BleedOption", BleedOption, UseAsIs, ScaleToBleed, FitInside);
    variants!("BleedSource", BleedSource, None, Detected, Manual);
    variants!("ImpositionMode", ImpositionMode, Repeat, Unique);
    variants!("DuplexFlipEdge", DuplexFlipEdge, LongEdge, ShortEdge);
    variants!(
        "GangUpExportType",
        GangUpExportType,
        CleanPdf,
        LegacyDuploCutPlan
    );
    variants!("OutputPreference", OutputPreference, CleanPdf);
    let request: actual::LayoutRequest = serde_json::from_value(json!({
        "sourceId": null, "sourcePages": [], "finishedSizeMode": "common",
        "artworkFit": {"mode":"stretch", "position":{"x":0.25,"y":0.75}},
        "pageOverrides":[{"pageNumber":1,"finishedCutSize":{"width":2.25,"height":1.75},"artworkFit":{"mode":"cover","position":{"x":1.0,"y":0.0}}},{"pageNumber":2,"finishedCutSize":{"width":2.25,"height":1.75},"artworkFit":null}],
        "sourcePdfSize":{"width":3.5,"height":2.0}, "sourceTrimBox":null, "sourcePageCount":2,
        "finishedCutSize":{"width":3.5,"height":2.0}, "parentSheetSize":{"width":12.0,"height":18.0},
        "quantityRequested":3,"impositionMode":"repeat","impressionQuantities":[3],
        "orientationPreference":"upright","sides":"double",
        "duplex":{"flipEdge":"shortEdge","rotateBack180":true,"backAlignment":"ignored request value"},
        "layoutMode":"maxPieces","bleedOption":"scaleToBleed","sourceBleedOverride":null,
        "createdBleedAmount":0.125,"gutter":{"horizontal":0.299,"vertical":0.299},"manual":null
    })).map_err(|e| crate::AppError::internal_cause("contract request", e))?;
    add!("LayoutRequest", &request);
    let layout = crate::imposition::generate_layout(request.clone())?;
    add!("LayoutResult", &layout);
    add!("ArtworkFit", &request.artwork_fit);
    add!("PageOverride", &request.page_overrides[0]);
    add!("DuplexSettings", &layout.duplex);
    let preset: actual::PresetInput = serde_json::from_value(json!({
        "id":null,"name":"Contract preset","impositionMode":"repeat","finishedSizeMode":"common",
        "artworkFit":request.artwork_fit,"finishedCutSize":request.finished_cut_size,
        "parentSheetSize":request.parent_sheet_size,"bleedHandling":"scaleToBleed",
        "sourceBleedOverride":0.125,"createdBleedAmount":0.125,"gutter":request.gutter,
        "orientationPreference":"upright","sides":"double","layoutPreference":"manual",
        "manual":{"rows":2,"columns":2,"rotationDegrees":90,"margins":{"top":1.0,"right":1.0,"bottom":1.0,"left":1.0}},
        "duplex":request.duplex,"outputPreference":"cleanPdf"
    })).map_err(|e| crate::AppError::internal_cause("contract preset", e))?;
    add!("PresetInput", &preset);
    let mut saved_preset = serde_json::to_value(&preset)
        .map_err(|e| crate::AppError::internal_cause("contract preset", e))?;
    saved_preset["id"] = json!("preset-7");
    saved_preset["builtIn"] = json!(false);
    let saved_preset: actual::GangUpPreset = serde_json::from_value(saved_preset)
        .map_err(|e| crate::AppError::internal_cause("contract saved preset", e))?;
    add!("GangUpPreset", saved_preset);
    let summary = actual::RecentGangUpLayoutSummary {
        pieces_per_sheet: layout.pieces_per_sheet,
        sheets_required: layout.sheets_required,
        total_pieces_produced: layout.total_pieces_produced,
        extra_pieces_produced: layout.extra_pieces_produced,
    };
    add!(
        "RecentGangUpJob",
        actual::RecentGangUpJob {
            id: "recent-7".into(),
            name: "Old saved setup".into(),
            source_filename: Some("a=b.pdf".into()),
            saved_at: "2026-10-06T12:00:00Z".into(),
            request: request.clone(),
            layout_summary: Some(summary.clone()),
        }
    );
    add!(
        "GangUpExportRecord",
        actual::GangUpExportRecord {
            id: "export-7".into(),
            name: "Stored PDF".into(),
            source_filename: None,
            exported_at: "2026-10-06T12:00:00Z".into(),
            output_type: actual::GangUpExportType::CleanPdf,
            output_filename: "a=b-imposed.pdf".into(),
            has_stored_file: true,
            request: request.clone(),
            layout_summary: Some(summary),
        }
    );
    let analysis: actual::PdfAnalysis = serde_json::from_value(json!({
        "filename":"mixed.pdf", "pageCount":2, "sourcePdfSize":request.source_pdf_size,
        "orientation":"landscape", "mediaBox":null, "cropBox":null, "bleedBox":null,
        "trimBox":null, "likelyBleed":{"detected":false,"amountPerSide":0.0,"horizontal":0.0,"vertical":0.0,"notes":["No uniform bleed detected"]},
        "matchedPresetId":null,"suggestedFinishedCutSize":null,"appearsDuplex":true,"warnings":[]
    })).map_err(|e| crate::AppError::internal_cause("contract analysis", e))?;
    add!("PdfAnalysis", &analysis);
    cases.push((
        "PreparedSourceResponse",
        json!({"sourceId":"source-7","analysis":analysis}),
    ));
    cases.push((
        "PreviewBatchRequest",
        json!({"pageNumbers":[1,2,3,4],"sourceBleedOverride":0.125}),
    ));
    let mut code = String::from("-- Generated from production Serde values. Do not edit.\nmodule RustWire exposing (cases)\n\ncases : List (String, String)\ncases =\n    [ ");
    for (index, (name, value)) in cases.iter().enumerate() {
        if index > 0 {
            code.push_str("\n    , ");
        }
        let value = serde_json::to_string(&value)
            .map_err(|e| crate::AppError::internal_cause("contract JSON", e))?;
        let literal = serde_json::to_string(&value)
            .map_err(|e| crate::AppError::internal_cause("contract string", e))?;
        code.push_str(&format!("(\"{name}\", {literal})"));
    }
    code.push_str("\n    ]\n");
    Ok(code)
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn generation_is_deterministic_and_enum_names_are_disjoint() {
        let code = generate();
        assert_eq!(code, generate());
        assert!(code.contains("OrientationPortrait"));
        assert!(code.contains("OrientationPreferencePortrait"));
        assert!(code.contains("GangUpExportTypeCleanPdf"));
        assert!(code.contains("OutputPreferenceCleanPdf"));
        assert!(code.contains("Json.Encode.string \"duploCutPlan\""));
        assert!(!code.contains("struct.backAlignment"));
        assert!(code.contains("Json.Decode.field \"backAlignment\""));
    }
    #[test]
    fn fixtures_are_production_serde_not_generation_defaults() {
        let fixtures = contract_fixtures().unwrap();
        assert!(fixtures.contains("LayoutResult"));
        assert!(!fixtures.contains("ignored request value"));
    }
}
